version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      composer-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      composer-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
      composer-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      npm-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"
