version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "stable"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "stable"
    schedule:
      interval: "monthly"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "stable"
    schedule:
      interval: "monthly"
    groups:
      composer-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      composer-major:
        patterns:
          - "*"
        update-types:
          - "major"
